"""Add_chemical_parameters

Revision ID: d58460bf2a1c
Revises: faf8e8e16f5f
Create Date: 2025-12-05 18:15:47.589968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd58460bf2a1c'
down_revision: Union[str, Sequence[str], None] = 'faf8e8e16f5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('ph', sa.String(), nullable=True))
    op.add_column('services', sa.Column('chlorine', sa.String(), nullable=True))
    op.add_column('services', sa.Column('alkalinity', sa.String(), nullable=True))
    op.add_column('services', sa.Column('remarks', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'remarks')
    op.drop_column('services', 'alkalinity')
    op.drop_column('services', 'chlorine')
    op.drop_column('services', 'ph')
    # ### end Alembic commands ###
